version: '3.4'

services:
  eventbuying.api:
    image: ${DOCKER_REGISTRY-}eventbuyingapi
    build:
      context: .
      dockerfile: services/EventBuying.API/Dockerfile

  eventslist.web:
    image: ${DOCKER_REGISTRY-}eventslistweb
    build:
      context: .
      dockerfile: EventsList.Web/Dockerfile

